---
title: "Final Report"
execute: 
  echo: true      # change to true to show the code
code-fold: false  # change to true to fold the code chunks
editor: 
  markdown: 
    wrap: sentence
---

Your report will go here.

```{r}
# this is a test code
```

# Motivation {.unnumbered}

Colette and I both utilize Letterboxd and enjoy films; we both are aware that the typical Letterboxd user tends to be a "cinephile", trending towards a movie snob rather than a casual enjoyer.
People may be surprised by a low Letterboxd average score for a film, but we both take it with a grain of salt because Letterboxd users often do not rate movies very high despite enjoying it.
However, is the idea of Letterboxd actually rating films lower than other rating websites true, or is this a bias we have that is only founded on the perceived culture of the app?
It is with this in mind we hope to explore top films' ratings on Letterboxd and IMDb to compare if Letterboxd actually rates them lower than the more popular site.
This information would help to better understand the culture of both rating sites, and help those looking at movie ratings better understand the rating of a film in context.

# Research Question {.unnumbered}

How do average Letterboxd scores compare to average IMDb scores for top films?
Does Letterboxd rate films lower than IMDb?

Our goal is to determine if the perceived culture of Letterboxd actually translates to how people rate films.
We hope to communicate information about typical ratings patterns on each website to help users make more informed movie selections.

# Background {.unnumbered}

```         
What background information is necessary for target audience to understand?
What assumptions, terms, and/or acronyms need to be clarified?
```

# Data {.unnumbered}

### Letterboxd Data {.unnumbered}

[Link to Kaggle Page](https://www.kaggle.com/datasets/riyosha/letterboxd-movie-reviews-90000)

This data was collected from the Letterboxd official top 250 movies page and then scraped using selenium and beautiful soup as of 4/09/24.
It was collected by Riyosha on Kaggle, which is where we collected the data.
The data consists of star ratings of each movie from the top 250, reviews for each rating if available, the date the movie was watched by the user, if the watch was a first-time watch or a rewatch, and the name of the movie.
There are over 90,000 reviews overall, with about 360 reviews for each movie.
There are both categorical and numerical measurements.
Before we start, we need to convert the star ratings to decimals, and make each rating out of 10 to match the IMDb rating.
There are also some NA values that need to be cleaned up.

### IMDb Data {.unnumbered}

[Link to Kaggle Page](https://www.kaggle.com/datasets/yusufdelikkaya/imdb-movie-dataset)

This data shows the ranking of the top 1000 movies, the title of each movie, the genre, a brief plot description, director, lead actors, year of release, runtime, rating out of ten, and user votes (how many users watched/rated).
This data was last updated 6 months ago.
The data was collected from the IMDb website, and licensed through public domain, and posted to Kaggle, where we found the data.
There are 1000 data points, one for each movie.
All variables except rating are categorical.
We have to clean movie titles in order to match and join them with the Letterboxd data, and select only the needed variables and data points to analyze this data.

# Data Insights {.unnumbered}

It’s your job to explicitly identify and discuss key insights.
Don’t simply present the audience with some code and output and expect them to do that work.
Specifically address the following questions:

```         
What are the important takeaways from the data? What was interesting?
Why do these takeaways matter?
Was there anything surprising?
Overall, what do you want the audience to walk away with? What do you want them to understand about your data and research questions?
```

# Conclusions / Big Picture {.unnumbered}

```         
How do the insights connect to answer your research question(s)?
```

# Limitations and Future Work {.unnumbered}

```         
What limitations or weaknesses does your data / analysis suffer from?
What improvements might someone make to your analysis?
```
