---
title: "Letterboxd Cleaning"
format: html
---
```{r}
library(tidyverse) 

# import data from data folder of repo
letterboxd_data <- read_csv("..\\data\\letterboxd_250movie_reviews.csv")
# letterboxd_data <- read_csv("/Users/colettelawler/Desktop/project-fake-cinephiles/data/letterboxd_250movie_reviews.csv")

letterboxd_data |>
  head()
```

```{r}
letterboxd_convertStars <-letterboxd_data |>
  mutate(numerical_rating = fct_recode(Rating, "5" = "★★★★★",
                                       "4.5" = "★★★★½", 
                                        "4" = "★★★★",
                                       "3.5" = "★★★½",
                                        "3" = "★★★",
                                        "2.5" = "★★½", 
                                        "2" = "★★",
                                       "1.5" =  "★½",
                                        "1" = "★",
                                       ".5" = "½"))
```

```{r}
#select only movie title and rating categories, and update the review to a 1-10 scale instead of 1-5, make movie titles spaced out and not dashes
letterboxd_clean <- letterboxd_convertStars |>
  filter(!is.na(numerical_rating)) |>
  mutate(
    numerical_rating = as.numeric(as.character(numerical_rating)),
    out_of_ten = numerical_rating *2) |>
  group_by(Movie) |>
  summarise(
    avg_rating = mean(out_of_ten, na.rm = TRUE),
  ) |> 
arrange(desc(avg_rating)) |>
  mutate(movie_titles = str_replace_all(Movie, "-", " ")) |>
  select(movie_titles, avg_rating)
```

```{r}
# preview code
head(letterboxd_clean)
```

